<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInStock()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.in_stock > 0');

        return $qb;
    }
}
