services:
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
    login_listener:
        class: 'Shop\UserBundle\EventListener\LoginListener'
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: kernel.event_subscriber }